---
title: Chatbot
hero_image: images/chatbot.png
description: Lerne, Deinen eigenen sprechenden Roboter zu programmieren!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technology: scratch
site_areas: projects
technologies: scratch
hardware: ''
software: scratch
version: 4.1.0
last_tested: 2017-01-01
steps:
  - title: Einleitung
  - title: Was du brauchen wirst
  - title: Dein Chatbot
  - title: Ein sprechender Chatbot
  - title: Entscheidungen treffen
  - title: Ortswechsel
  - title: 'Herausforderung: Vervollständige deinen Chatbot'
